# docker-compose.yml

services:
  # Бэкенд сервис на FastAPI
  backend:
    build: ./server
    env_file: ./.env
    container_name: eduanalytics_backend
    command: >
      sh -c "alembic upgrade head && 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # Сервис базы данных PostgreSQL
  db:
    image: postgres:13-alpine
    container_name: eduanalytics_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eduanalytics_db
    ports:
      - "5432:5432"
    healthcheck:
      # --- ИСПРАВЛЕНИЕ ЗДЕСЬ: Добавляем имя базы данных ---
      test: ["CMD-SHELL", "pg_isready -U user -d eduanalytics_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис кэширования Redis
  cache:
    image: redis:6-alpine
    container_name: eduanalytics_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: