# docker-compose.yml

services:
  # Бэкенд сервис на FastAPI
  backend:
    build: ./server
    env_file: ./.env
    container_name: eduanalytics_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      # --- ИСПРАВЛЕНИЕ ЗДЕСЬ: Добавлен драйвер +asyncpg ---
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/eduanalytics_db
      - REDIS_URL=redis://cache
    depends_on:
      - db
      - cache

  # Сервис базы данных PostgreSQL
  db:
    image: postgres:13-alpine
    container_name: eduanalytics_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eduanalytics_db
    ports:
      - "5432:5432"

  # Сервис кэширования Redis
  cache:
    image: redis:6-alpine
    container_name: eduanalytics_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: