"""Fix Quiz relationships

Revision ID: 108131f6a8b9
Revises: fdb2c2e0d5fb
Create Date: 2025-08-16 20:10:39.972620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108131f6a8b9'
down_revision: Union[str, Sequence[str], None] = 'fdb2c2e0d5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('quizzes_created_by_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['created_by_id'], ['id'])
    op.drop_column('quizzes', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_created_by_fkey'), 'quizzes', 'users', ['created_by'], ['id'])
    op.drop_column('quizzes', 'created_by_id')
    # ### end Alembic commands ###
