"""add file fields to submissions

Revision ID: 2401f33bb680
Revises: 89c4b8a7d12f
Create Date: 2025-08-14 09:51:25.606047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2401f33bb680'
down_revision: Union[str, Sequence[str], None] = '89c4b8a7d12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('file_path', sa.String(length=500), nullable=True, comment='Путь к загруженному файлу'))
    op.add_column('submissions', sa.Column('file_name', sa.String(length=255), nullable=True, comment='Оригинальное имя файла'))
    op.add_column('submissions', sa.Column('file_size', sa.Integer(), nullable=True, comment='Размер файла в байтах'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'file_size')
    op.drop_column('submissions', 'file_name')
    op.drop_column('submissions', 'file_path')
    # ### end Alembic commands ###
