"""add pages and discussions

Revision ID: c351354835ff
Revises: 8333dbe8992b
Create Date: 2025-08-16 23:01:19.261694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c351354835ff'
down_revision: Union[str, Sequence[str], None] = '8333dbe8992b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_topics_author_id'), 'discussion_topics', ['author_id'], unique=False)
    op.create_index(op.f('ix_discussion_topics_course_id'), 'discussion_topics', ['course_id'], unique=False)
    op.create_index(op.f('ix_discussion_topics_id'), 'discussion_topics', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'slug', name='uq_pages_course_slug')
    )
    op.create_index(op.f('ix_pages_author_id'), 'pages', ['author_id'], unique=False)
    op.create_index(op.f('ix_pages_course_id'), 'pages', ['course_id'], unique=False)
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('discussion_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_entries.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['discussion_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_entries_id'), 'discussion_entries', ['id'], unique=False)
    op.create_index(op.f('ix_discussion_entries_parent_id'), 'discussion_entries', ['parent_id'], unique=False)
    op.create_index(op.f('ix_discussion_entries_topic_id'), 'discussion_entries', ['topic_id'], unique=False)
    op.create_index(op.f('ix_discussion_entries_user_id'), 'discussion_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discussion_entries_user_id'), table_name='discussion_entries')
    op.drop_index(op.f('ix_discussion_entries_topic_id'), table_name='discussion_entries')
    op.drop_index(op.f('ix_discussion_entries_parent_id'), table_name='discussion_entries')
    op.drop_index(op.f('ix_discussion_entries_id'), table_name='discussion_entries')
    op.drop_table('discussion_entries')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_course_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_author_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_discussion_topics_id'), table_name='discussion_topics')
    op.drop_index(op.f('ix_discussion_topics_course_id'), table_name='discussion_topics')
    op.drop_index(op.f('ix_discussion_topics_author_id'), table_name='discussion_topics')
    op.drop_table('discussion_topics')
    # ### end Alembic commands ###
