"""change lesson_type to varchar

Revision ID: f6eb5177e0d9
Revises: 2401f33bb680
Create Date: 2025-08-14 20:01:03.513437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6eb5177e0d9'
down_revision: Union[str, Sequence[str], None] = '2401f33bb680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Изменяем тип колонки lesson_type с enum на VARCHAR
    op.execute("ALTER TABLE schedules ALTER COLUMN lesson_type TYPE VARCHAR(20) USING lesson_type::text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем тип колонки lesson_type обратно к enum
    op.execute("ALTER TABLE schedules ALTER COLUMN lesson_type TYPE lessontype USING lesson_type::lessontype")
    # ### end Alembic commands ###
