# .github/workflows/ci.yml

# Название нашего пайплайна, которое будет отображаться в GitHub
name: CI Build and Test

# Триггер для запуска: push в ветку main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Задачи, которые будут выполняться
jobs:
  # Первая задача: проверка frontend-приложения
  frontend-check:
    # Указываем, на какой операционной системе выполнять задачу
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js нужной версии
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите версию, которую вы используете

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      # Шаг 4: Собираем проект для проверки и загружаем source maps в Sentry
      - name: Build project
        run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

  # Вторая задача: проверка backend-приложения
  backend-check:
    # Также запускаем на Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python нужной версии
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Укажите вашу версию Python

      # Шаг 3: Устанавливаем зависимости из requirements.txt
      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}